import { ResourceRegistry } from "../helpers/types";
import { accountResource } from "./accounts";
import { domainResource } from "./domains";
import { contactResource } from "./contacts";
import { registrarResource } from "./registrar";
import { zoneResource } from "./zones";
import { zoneRecordResource } from "./zoneRecords";
import { templateResource } from "./templates";
import { templateRecordResource } from "./templateRecords";
import { serviceResource } from "./services";
import { certificateResource } from "./certificates";
import { webhookResource } from "./webhooks";
import { tldResource } from "./tlds";
import { dnsAnalyticsResource } from "./dnsAnalytics";
import { vanityNameServerResource } from "./vanityNameServers";
import { dnssecResource } from "./dnssec";
import { emailForwardResource } from "./emailForwards";
import { domainPushResource } from "./domainPushes";

export const registry = new ResourceRegistry();

registry.register(accountResource);
registry.register(domainResource);
registry.register(contactResource);
registry.register(registrarResource);
registry.register(zoneResource);
registry.register(zoneRecordResource);
registry.register(templateResource);
registry.register(templateRecordResource);
registry.register(serviceResource);
registry.register(certificateResource);
registry.register(webhookResource);
registry.register(tldResource);
registry.register(dnsAnalyticsResource);
registry.register(vanityNameServerResource);
registry.register(dnssecResource);
registry.register(emailForwardResource);
registry.register(domainPushResource);

export { accountResource } from "./accounts";
export { domainResource } from "./domains";
export { contactResource } from "./contacts";
export { registrarResource } from "./registrar";
export { zoneResource } from "./zones";
export { zoneRecordResource } from "./zoneRecords";
export { templateResource } from "./templates";
export { templateRecordResource } from "./templateRecords";
export { serviceResource } from "./services";
export { certificateResource } from "./certificates";
export { webhookResource } from "./webhooks";
export { tldResource } from "./tlds";
export { dnsAnalyticsResource } from "./dnsAnalytics";
export { vanityNameServerResource } from "./vanityNameServers";
export { dnssecResource } from "./dnssec";
export { emailForwardResource } from "./emailForwards";
export { domainPushResource } from "./domainPushes";
