import { ResourceRegistry } from "@dnsimple-types/registry";
import { accountResource } from "@resources/accounts";
import { domainResource } from "@resources/domains";
import { contactResource } from "@resources/contacts";
import { registrarResource } from "@resources/registrar";
import { zoneResource } from "@resources/zones";
import { zoneRecordResource } from "@resources/zoneRecords";
import { templateResource } from "@resources/templates";
import { templateRecordResource } from "@resources/templateRecords";
import { serviceResource } from "@resources/services";
import { certificateResource } from "@resources/certificates";
import { webhookResource } from "@resources/webhooks";
import { tldResource } from "@resources/tlds";
import { dnsAnalyticsResource } from "@resources/dnsAnalytics";
import { vanityNameServerResource } from "@resources/vanityNameServers";
import { dnssecResource } from "@resources/dnssec";
import { emailForwardResource } from "@resources/emailForwards";
import { domainPushResource } from "@resources/domainPushes";

export const registry = new ResourceRegistry();

registry.register(accountResource);
registry.register(domainResource);
registry.register(contactResource);
registry.register(registrarResource);
registry.register(zoneResource);
registry.register(zoneRecordResource);
registry.register(templateResource);
registry.register(templateRecordResource);
registry.register(serviceResource);
registry.register(certificateResource);
registry.register(webhookResource);
registry.register(tldResource);
registry.register(dnsAnalyticsResource);
registry.register(vanityNameServerResource);
registry.register(dnssecResource);
registry.register(emailForwardResource);
registry.register(domainPushResource);

export { accountResource } from "@resources/accounts";
export { domainResource } from "@resources/domains";
export { contactResource } from "@resources/contacts";
export { registrarResource } from "@resources/registrar";
export { zoneResource } from "@resources/zones";
export { zoneRecordResource } from "@resources/zoneRecords";
export { templateResource } from "@resources/templates";
export { templateRecordResource } from "@resources/templateRecords";
export { serviceResource } from "@resources/services";
export { certificateResource } from "@resources/certificates";
export { webhookResource } from "@resources/webhooks";
export { tldResource } from "@resources/tlds";
export { dnsAnalyticsResource } from "@resources/dnsAnalytics";
export { vanityNameServerResource } from "@resources/vanityNameServers";
export { dnssecResource } from "@resources/dnssec";
export { emailForwardResource } from "@resources/emailForwards";
export { domainPushResource } from "@resources/domainPushes";
